name: verify json

on:
  pull_request:
    branches:
      - master

jobs:
  excavate:
    permissions:
      contents: read
    runs-on: windows-2025
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Validator
        uses: ScoopInstaller/GithubActions@797d33021c0fbd52be705ce8136d9d62c5b41782 # main (Nov 25, 2025)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
